"""Compatibility facade for TokenClaw stats views.

Core dashboard aggregation lives in :mod:`tokenclaw.stats.core`. Specialized
stats views live in sibling modules. This package preserves the historical
``tokenclaw.stats`` import surface while new code migrates to owner modules.
"""

from __future__ import annotations

from types import ModuleType
from typing import Any

from tokenclaw.stats import core as _core


def _export_module(module: ModuleType) -> None:
    for name, value in vars(module).items():
        if name.startswith("__") and name.endswith("__"):
            continue
        globals()[name] = value


_export_module(_core)


from tokenclaw.stats.activation import (
    ACTIVATION_SUCCESSOR_BURNDOWN_FAMILIES,
    PREVIEW_AGREEMENT_BUCKETS,
    PREVIEW_AGREEMENT_EXTRA_COUNTS,
    _EVIDENCE_NEXT_ACTION_ENTRY_FIELDS,
    _activation_issue_queue_reason,
    _activation_issue_queue_status,
    _activation_preview_agreement_burndown,
    _activation_public_ref,
    _activation_status_bucket,
    _activation_successor_burndown,
    _activation_successor_family,
    _activation_successor_health_empty,
    _activation_successor_health_from_queue,
    _activation_successor_preview_gate,
    _activation_successor_top_entry,
    _activation_top_blocker,
    _closed_loop_activation_entry_states,
    _closed_loop_activation_family,
    _closed_loop_activation_readiness,
    _closed_loop_activation_text,
    _closed_loop_entry_stale_age_hours,
    _count_activation_values,
    _empty_evidence_next_actions_payload,
    _empty_local_activation_queue_payload,
    _empty_managed_preview_coverage,
    _empty_preview_gated_activation_issue_queue_payload,
    _evidence_to_activation_plan_candidate_paths,
    _evidence_to_activation_plan_path,
    _extract_local_activation_queue_from_plan,
    _local_activation_queue_privacy,
    _managed_activation_preview_coverage,
    _managed_preview_coverage_for_family,
    _managed_preview_coverage_privacy,
    _managed_preview_data_status,
    _managed_preview_family_row,
    _managed_preview_public_outcome,
    _managed_preview_reason,
    _post_promotion_action_counts,
    _post_promotion_artifact_source,
    _post_promotion_delta_row,
    _post_promotion_family,
    _post_promotion_handoff_freshness,
    _post_promotion_latest_blocker,
    _post_promotion_next_action,
    _post_promotion_next_safe_command,
    _post_promotion_noop_reasons,
    _post_promotion_outcome_flush_status_path,
    _post_promotion_policy_draft_dry_run_path,
    _post_promotion_priority_handoff_privacy,
    _post_promotion_priority_review_path,
    _post_promotion_privacy_summary,
    _post_promotion_state,
    _post_promotion_status,
    _post_promotion_status_counts,
    _preview_agreement_bucket,
    _preview_agreement_extra_counts,
    _preview_agreement_reason,
    _preview_gated_activation_issue_queue_payload,
    _promotion_action_dashboard_row,
    _promotion_blocker_dashboard_privacy,
    _promotion_blocker_no_data,
    _promotion_blocker_public_group,
    _promotion_blocker_reason_counts,
    _promotion_blocker_review_path,
    _promotion_blocker_stale_count,
    _promotion_canary_meta_from_decision,
    _promotion_executor_readiness,
    _promotion_finalize_observed,
    _promotion_impact_stale,
    _promotion_lifecycle_rows,
    _promotion_new_observed_bucket,
    _promotion_next_command,
    _promotion_observed_canary_rows,
    _promotion_omission_dashboard_bucket,
    _promotion_pending_lifecycle_rows,
    _promotion_policy_section,
    _promotion_primary_state,
    _promotion_privacy_summary,
    _promotion_reason_has_any,
    _promotion_target_local_policy_section,
    _proposal_status_label,
    _public_activation_successor_health_entry,
    _public_evidence_next_action_entry,
    _public_local_activation_queue_entry,
    _public_local_activation_queue_summary,
    _public_preview_gated_issue_proposal,
    _public_preview_gated_successor_decision,
    _read_post_promotion_artifact,
    _status_count_rows,
    _summary_preview_agreement_rows,
    _top_issue,
    build_activation_successor_queue_health,
    stats_activation_preview_burndown,
    stats_evidence_to_activation_next_actions,
    stats_local_activation_next_action_queue,
    stats_optimization_promotion_actions,
    stats_optimization_promotion_funnel,
    stats_post_promotion_deltas,
    stats_post_promotion_priority_handoff,
    stats_preview_gated_activation_issue_queue,
    stats_promotion_blocker_next_actions,
)


from tokenclaw.stats.dashboard_html import dashboard_html

from tokenclaw.stats.managed import (
    _claude_public_metadata_label,
    _claude_route_blocker_reason,
    _claude_route_count,
    _claude_route_finalize_candidate,
    _claude_route_group_key,
    _claude_route_increment_breakdown,
    _claude_route_is_eligible,
    _claude_route_public_label,
    _claude_route_stage_from_canary,
    _claude_route_touch,
    _claude_routing_funnel_privacy,
    _collect_action_family,
    _day_key,
    _finalize_openai_scoreboard_bucket,
    _finalize_phase_canary_bucket,
    _find_nested_dict,
    _managed_attempt_status,
    _managed_breakdown,
    _managed_decision_source,
    _managed_error_class,
    _managed_feed_decision_summary,
    _managed_feed_state,
    _managed_feedback_error_class,
    _managed_feedback_inferred_action_family,
    _managed_feedback_payload_action_families,
    _managed_feedback_queue_expectation,
    _managed_feedback_queue_health,
    _managed_feedback_safe_error_class,
    _managed_openai_activation_staged_drafts,
    _managed_openai_activation_status,
    _managed_pattern_add_adoption_row,
    _managed_pattern_adoption_from_store,
    _managed_pattern_blocker_reasons,
    _managed_pattern_finalize_adoption_rows,
    _managed_pattern_holdout_comparisons,
    _managed_pattern_is_bypass,
    _managed_pattern_summary_stage,
    _managed_policy_event_sections,
    _managed_policy_event_stage,
    _managed_policy_lifecycle_rows,
    _MANAGED_SUCCESS_STATUSES,
    _new_claude_route_funnel_candidate,
    _new_openai_scoreboard_bucket,
    _new_phase_canary_bucket,
    _normalize_feedback_dimension,
    _openai_activation_conflict_summary,
    _openai_activation_counts_by_family,
    _openai_activation_review_metadata,
    _openai_canary_candidate_rows,
    _openai_canary_policy_state,
    _openai_canary_readiness_state,
    _openai_canary_top_blockers,
    _openai_candidate_id,
    _openai_dashboard_dimension,
    _openai_dashboard_reason_codes,
    _openai_governor_endpoint,
    _openai_governor_from_metadata,
    _openai_quality_gate_outcome,
    _openai_recommendation_state,
    _phase_canary_cohort,
    _phase_routing_feedback_rows,
    _phase_routing_public_health_rows,
    _phase_routing_public_lifecycle_rows,
    _public_managed_feedback_row,
    _public_managed_openai_activation_event,
    _routing_candidate_lifecycle_privacy,
    _routing_candidate_lifecycle_source,
    _routing_candidate_stage_row,
    _safe_latest_managed_activation_proof,
    _safe_public_bool_env_configured,
    _safe_thinking_tail_loop_status,
    _safe_thinking_tail_readiness,
    _shadow_routing_candidate_id,
    _shadow_routing_candidate_rows,
    _shadow_routing_readiness_state,
    _shadow_routing_row_key,
    _shadow_routing_scoreboard_to_candidate_row,
    MANAGED_OPENAI_ACTIVATION_ACTIONS,
    MANAGED_OPENAI_SUPPORTED_ACTION_FAMILIES,
    ROUTING_CANDIDATE_LIFECYCLE_STATES,
    stats_claude_canary_impact,
    stats_claude_routing_promotion_funnel,
    stats_managed_activation_status,
    stats_managed_feedback_queue_freshness,
    stats_managed_openai_activation,
    stats_managed_recommendations,
    stats_openai_canary_readiness,
    stats_openai_optimization_readiness,
    stats_openai_routing_report,
    stats_openai_scoreboard,
    stats_phase_routing,
    stats_routing_candidate_lifecycle_burndown,
    stats_routing_coverage_report,
    stats_shadow_routing_promotion_readiness,
)

from tokenclaw.stats.codex import (
    _codex_turn_estimates,
    _codex_estimates_with_cache,
    _codex_not_applied_decision,
    _codex_turn_risk_features,
    _codex_summary_hint_status,
    _codex_summary_hint_estimated_savings,
    _new_codex_summary_hint_bucket,
    _add_codex_summary_hint_bucket,
    _finalize_codex_summary_hint_buckets,
    _codex_summary_hint_status_totals,
    _codex_summary_hint_canary_summary,
    _codex_crunch_pattern_breakdown,
    _codex_decision_metadata_state,
    _codex_missing_decision,
    _codex_normalized_decision,
    _codex_model_field_state,
    _codex_param_shape_category,
    _codex_phase_signal,
    _codex_phase_from_signal_counts,
    _codex_signal_counts_from_method_counts,
    _codex_public_event_window,
    _codex_same_scope,
    _codex_turn_bounds,
    _codex_count_bucket,
    _empty_codex_token_totals,
    _codex_public_scope_hash,
    _codex_public_token_usage,
    _codex_token_usage_delta,
    _codex_token_usage_cost,
    _codex_turn_token_estimates,
    _codex_turn_model,
    _codex_usage_matching_turn,
    _codex_usage_reconciliation_status,
    _codex_token_usage_reconciliation_state,
    _add_codex_token_totals,
    _codex_quota_token_usage_report,
    _codex_workflow_phase,
    _new_codex_phase_bucket,
    _finalize_codex_phase_bucket,
    _codex_plateau_scope,
    _codex_original_session_key,
    _codex_metadata_workflow_groups,
    _codex_phase_from_decision_metadata,
    _codex_meaningful_crunch,
    _codex_plateau_candidate_report,
    stats_codex_effectiveness,
    _codex_rule_report_meta,
    _codex_rule_report_cohort,
    _new_codex_rule_report_bucket,
    _finalize_codex_rule_report_bucket,
    stats_codex_canary_impact,
    _codex_cache_readiness_cohort,
    _codex_cache_readiness_cohorts,
    _codex_readiness_check,
    _openai_codex_blocker,
    stats_openai_codex_readiness,
    stats_codex_readiness,
    _codex_turn_activity_unit,
    _codex_accounting_unit,
    _breakdown_lookup,
    _token_drift_bucket,
)

from tokenclaw.stats.cache_replay import (
    _CACHE_BLOCKER_SCAN_LIMIT,
    _cache_decision_breakdown,
    _cache_replay_cohort_ranking_from_units,
    _cache_replayability_units_from_store,
    _cache_zero_hit_blocker_ladder,
    stats_cache_effectiveness,
    stats_cache_replay_activation_health,
    stats_cache_replay_cohort_ranking,
    stats_cache_replay_confidence,
    stats_cache_replay_dry_run,
    stats_cache_replay_readiness,
    stats_cache_replayability,
    stats_streaming_cache_hit_recovery,
)


def _sync_core_exports() -> None:
    for name, value in globals().items():
        if name.startswith("__") and name.endswith("__"):
            continue
        setattr(_core, name, value)


_sync_core_exports()


def __getattr__(name: str) -> Any:
    try:
        return getattr(_core, name)
    except AttributeError as exc:
        raise AttributeError(f"module {__name__!r} has no attribute {name!r}") from exc


def __dir__() -> list[str]:
    return sorted({*globals(), *dir(_core)})
