from __future__ import annotations

import copy
import json
import re
from dataclasses import dataclass
from typing import Any

from tokenclaw.managed_egress import managed_egress_violations
from tokenclaw.prompt_features import PROMPT_DIFFICULTY_FEATURE_SCHEMA, prompt_difficulty_features_from_text
from tokenclaw.store import stable_json
from tokenclaw.terminal_features import TERMINAL_LOG_FEATURE_SCHEMA, terminal_log_features_from_text


PATTERN_MODULES_SCHEMA = "agentflow.local_pattern_modules.v1"
PATTERN_MODULE_FEATURES_SCHEMA = "agentflow.local_pattern_module_features.v1"
TOOL_RESULT_FEATURE_SCHEMA = "agentflow.tool_result_features.v1"
DIFF_FEATURE_SCHEMA = "agentflow.diff_features.v1"
GENERATED_ARTIFACT_FEATURE_SCHEMA = "agentflow.generated_artifact_features.v1"
TABULAR_DATA_FEATURE_SCHEMA = "agentflow.tabular_data_features.v1"
CACHEABILITY_FEATURE_SCHEMA = "agentflow.cacheability_features.v1"
TOKEN_CHARS = 4


_DIFF_HEADER_RE = re.compile(r"^(?:diff --git |index [0-9a-f]{6,}\.\.|--- |\+\+\+ |rename (?:from|to) |new file mode |deleted file mode )")
_DIFF_HUNK_RE = re.compile(r"^@@\s+-\d+(?:,\d+)?\s+\+\d+(?:,\d+)?\s+@@")
_EXACT_REQUEST_RE = re.compile(
    r"\b(?:exact|verbatim|full file|entire file|do not (?:truncate|summari[sz]e)|without (?:truncat|summari[sz])|selected file|specific file)\b",
    re.IGNORECASE,
)
_LOCKFILE_RE = re.compile(
    r"\b(?:package-lock\.json|npm-shrinkwrap\.json|yarn\.lock|pnpm-lock\.yaml|poetry\.lock|Pipfile\.lock|Cargo\.lock|Gemfile\.lock|composer\.lock|go\.sum)\b"
)
_DEPENDENCY_TASK_RE = re.compile(
    r"\b(?:dependency|dependencies|lockfile|lock file|resolve|resolution|version conflict|semver|package manager|npm install|pnpm install|yarn install|poetry lock)\b",
    re.IGNORECASE,
)
_GENERATED_MARKER_RE = re.compile(
    r"\b(?:generated (?:by|code)|auto-generated|autogenerated|do not edit|@generated|Code generated by|protoc|protobuf|openapi-generator|swagger-codegen)\b",
    re.IGNORECASE,
)
_COMPILED_ARTIFACT_RE = re.compile(
    r"\b(?:dist/|build/|target/|\.min\.(?:js|css)|\.bundle\.(?:js|css)|sourceMappingURL=|__webpack_require__|webpackBootstrap|compiled artifact)\b",
    re.IGNORECASE,
)
_GREP_RESULT_RE = re.compile(r"^\s*[^:\s][^:\n]{0,240}:\d+(?::\d+)?:")
_SQL_TABLE_RE = re.compile(r"^\s*\|.*\|\s*$")
_SQL_BORDER_RE = re.compile(r"^\s*[+\-|=\s:]{6,}\s*$")
_ISSUE_LIST_RE = re.compile(r"(?:^|\s)(?:#\d{1,8}|[A-Z][A-Z0-9]{1,10}-\d{1,8})(?:\s|$)|github\.com/.+/(?:issues|pull)/\d+", re.IGNORECASE)
_TEST_RESULT_RE = re.compile(
    r"\b(?:FAILED|FAILURES|ERROR|AssertionError|Traceback|passed|failed|skipped|Ran\s+\d+\s+tests?|"
    r"short test summary info|test session starts|exit code\s+[1-9]\d*)\b",
    re.IGNORECASE,
)
_COMMAND_STREAM_RE = re.compile(r"^\s*(?:stdout|stderr|exit\s+code|return\s+code)\s*[:=]", re.IGNORECASE)
_FILE_LISTING_RE = re.compile(
    r"^\s*(?:[-dl][rwxstST-]{9}\s+|\d{1,8}\s+[\w./-]+$|(?:\.{0,2}/)?[\w .@+=:,~-]+(?:/|\.(?:py|js|ts|tsx|json|yaml|yml|md|txt|toml|sql|go|rs|java|sh|css|html))\s*$)"
)
_ERROR_RE = re.compile(r"\b(?:ERROR|ERR|FATAL|CRITICAL|Exception|Traceback|AssertionError|failed|failure|panic|exit code\s+[1-9]\d*)\b", re.IGNORECASE)
_TOOL_FRAMING_RE = re.compile(
    r"^\s*(?:"
    r"</?tool[_ -]?results?>"
    r"|(?:begin|end)\s+(?:tool|function)\s+results?"
    r"|(?:tool|function)\s+results?\s*:?"
    r"|(?:[-=]{2,})\s*(?:tool|function)\s+results?\s*(?:[-=]{2,})"
    r")\s*$",
    re.IGNORECASE,
)
_PIPE_SEPARATOR_RE = re.compile(r"^\s*\|?\s*:?-{3,}:?\s*(?:\|\s*:?-{3,}:?\s*)+\|?\s*$")
_SQL_BORDER_LINE_RE = re.compile(r"^\s*\+[-=+]+\+\s*$")
_JSON_ARRAY_START_RE = re.compile(r"\[")
_EXACT_LOOKUP_RE = re.compile(
    r"\b(?:exact(?:ly)?|specific|lookup|look up|find|which row|what row|row id|record id|id\s*[=:]?\s*\d+|"
    r"order\s+#?\d+|invoice\s+#?\d+|ticket\s+#?\d+|voucher\s+#?\d+|verbatim|full row|full record)\b",
    re.IGNORECASE,
)
_AGGREGATION_RE = re.compile(
    r"\b(?:count|counts|sum|total|average|avg|median|min|max|group by|aggregate|aggregation|distribution|"
    r"histogram|top\s+\d+|percent|percentage|rate|trend|summari[sz]e|sample|representative)\b",
    re.IGNORECASE,
)
_RECONCILIATION_RE = re.compile(
    r"\b(?:reconcile|reconciliation|mismatch|mismatches|discrepanc|compare|cross-check|audit|balance|"
    r"tie out|diff|delta|missing row|duplicate|duplicates|validate every|verify every)\b",
    re.IGNORECASE,
)
_CURRENT_STATE_RE = re.compile(
    r"\b(?:current|currently|latest|today|tonight|now|right now|real[- ]time|live|recent|as of|up to date|"
    r"up-to-date|weather|stock price|exchange rate|news|availability|status page|open issues?|local files?|"
    r"workspace|repository|repo|database|production|prod)\b",
    re.IGNORECASE,
)
_USER_SPECIFIC_RE = re.compile(
    r"\b(?:my|mine|me|I|I'm|I've|we|our|ours|us|account|profile|subscription|invoice|billing|private|"
    r"customer|user-specific|personal|local|workspace|repository|repo|project|company|tenant)\b",
    re.IGNORECASE,
)
_STATIC_INFORMATION_RE = re.compile(
    r"\b(?:what is|what are|who is|who was|where is|where are|define|definition of|explain|describe|"
    r"how does|why does|capital of|convert|syntax for|meaning of|overview of)\b",
    re.IGNORECASE,
)


def _count_bucket(value: int) -> str:
    if value <= 0:
        return "zero"
    if value == 1:
        return "one"
    if value <= 3:
        return "two_three"
    if value <= 10:
        return "four_ten"
    return "gte_11"


def _text_bucket(chars: int) -> str:
    if chars < 2_000:
        return "lt_2k_chars"
    if chars < 8_000:
        return "2k_8k_chars"
    if chars < 32_000:
        return "8k_32k_chars"
    if chars < 128_000:
        return "32k_128k_chars"
    return "gte_128k_chars"


def _fraction_bucket(numerator: int, denominator: int) -> str:
    if denominator <= 0 or numerator <= 0:
        return "none"
    ratio = numerator / denominator
    if ratio < 0.10:
        return "lt_10pct"
    if ratio < 0.25:
        return "10_25pct"
    if ratio < 0.50:
        return "25_50pct"
    if ratio < 0.75:
        return "50_75pct"
    return "gte_75pct"


def _extract_text(value: Any) -> str:
    parts: list[str] = []
    if isinstance(value, str):
        parts.append(value)
    elif isinstance(value, list):
        for item in value:
            text = _extract_text(item)
            if text:
                parts.append(text)
    elif isinstance(value, dict):
        for key, child in value.items():
            if key in {"text", "content", "input", "system", "instructions"}:
                text = _extract_text(child)
                if text:
                    parts.append(text)
            elif isinstance(child, (list, dict)):
                text = _extract_text(child)
                if text:
                    parts.append(text)
    return "\n".join(parts)


@dataclass(frozen=True)
class PatternModuleContext:
    body: dict[str, Any]
    text: str
    category: str | None
    policy_source: str
    rule_path: str | None = None


@dataclass(frozen=True)
class PatternDetection:
    detected: bool
    reason: str
    confidence: str = "unknown"


@dataclass(frozen=True)
class PatternCrunchResult:
    body: dict[str, Any]
    changed: bool
    saved_chars: int = 0
    reason: str = "no-local-crunch"


class LocalPatternModule:
    family = "unknown"
    version = "1"
    feature_schema = "agentflow.local_pattern_module.generic_features.v1"
    enabled_by_default = True
    supports_local_crunch = False

    def detect(self, context: PatternModuleContext) -> PatternDetection:
        raise NotImplementedError

    def features(self, context: PatternModuleContext, detection: PatternDetection) -> dict[str, Any]:
        raise NotImplementedError

    def apply_local_crunch(
        self,
        body: dict[str, Any],
        context: PatternModuleContext,
        detection: PatternDetection,
    ) -> PatternCrunchResult:
        return PatternCrunchResult(body=body, changed=False)

    def outcome_metadata(
        self,
        *,
        status: str,
        reason: str,
        detection: PatternDetection | None,
        features: dict[str, Any] | None,
        changed: bool,
        saved_chars: int,
    ) -> dict[str, Any]:
        return {
            "schema": "agentflow.local_pattern_module_outcome.v1",
            "family": self.family,
            "version": self.version,
            "status": status,
            "reason": reason,
            "detected": bool(detection.detected) if detection else False,
            "detection_confidence": detection.confidence if detection else "unknown",
            "features_emitted": isinstance(features, dict),
            "feature_schema": self.feature_schema if isinstance(features, dict) else None,
            "changed": bool(changed),
            "saved_chars": max(0, int(saved_chars)),
            "tokens_saved_est": max(0, int(saved_chars) // TOKEN_CHARS),
        }


class PatternModuleRegistry:
    def __init__(self, modules: list[LocalPatternModule] | None = None):
        self._modules: dict[str, LocalPatternModule] = {}
        for module in modules or []:
            self.register(module)

    def register(self, module: LocalPatternModule) -> None:
        family = str(module.family or "").strip()
        if not family:
            raise ValueError("pattern module family is required")
        if family in self._modules:
            raise ValueError(f"pattern module already registered: {family}")
        self._modules[family] = module

    def families(self) -> list[str]:
        return sorted(self._modules)

    def modules(self) -> list[LocalPatternModule]:
        return [self._modules[family] for family in self.families()]

    def get(self, family: str) -> LocalPatternModule | None:
        return self._modules.get(family)


class TerminalLogPatternModule(LocalPatternModule):
    family = "terminal_logs"
    version = "2026-06-09.1"
    feature_schema = TERMINAL_LOG_FEATURE_SCHEMA
    supports_local_crunch = False

    def detect(self, context: PatternModuleContext) -> PatternDetection:
        features = terminal_log_features_from_text(context.text)
        detected = (
            features.get("terminal_output_char_fraction_bucket") != "none"
            or features.get("stack_trace_present") is True
            or features.get("test_output_present") is True
            or features.get("command_transcript_present") is True
        )
        return PatternDetection(
            detected=bool(detected),
            reason="terminal-log-signals-detected" if detected else "no-terminal-log-signals",
            confidence="high" if detected else "none",
        )

    def features(self, context: PatternModuleContext, detection: PatternDetection) -> dict[str, Any]:
        result = terminal_log_features_from_text(context.text)
        result.update({
            "module_family": self.family,
            "module_version": self.version,
            "detected": detection.detected,
        })
        return result


class PromptRolePatternModule(LocalPatternModule):
    family = "prompt_role"
    version = "2026-06-09.1"
    feature_schema = PROMPT_DIFFICULTY_FEATURE_SCHEMA
    supports_local_crunch = False

    def detect(self, context: PatternModuleContext) -> PatternDetection:
        detected = bool(context.text.strip())
        return PatternDetection(
            detected=detected,
            reason="prompt-role-signals-detected" if detected else "empty-prompt-text",
            confidence="medium" if detected else "none",
        )

    def features(self, context: PatternModuleContext, detection: PatternDetection) -> dict[str, Any]:
        result = prompt_difficulty_features_from_text(context.text)
        result.update({
            "module_family": self.family,
            "module_version": self.version,
            "detected": detection.detected,
        })
        return result


def _iter_tool_result_blocks(body: dict[str, Any]) -> list[dict[str, Any]]:
    blocks: list[dict[str, Any]] = []
    messages = body.get("messages")
    if not isinstance(messages, list):
        return blocks
    for msg_index, message in enumerate(messages):
        if not isinstance(message, dict):
            continue
        content = message.get("content")
        if not isinstance(content, list):
            continue
        for block_index, block in enumerate(content):
            if isinstance(block, dict) and block.get("type") == "tool_result":
                blocks.append({
                    "message_index": msg_index,
                    "block_index": block_index,
                    "block": block,
                })
    return blocks


def _tool_result_text_parts(value: Any) -> list[str]:
    if isinstance(value, str):
        return [value]
    if isinstance(value, list):
        parts: list[str] = []
        for item in value:
            parts.extend(_tool_result_text_parts(item))
        return parts
    if isinstance(value, dict):
        parts = []
        for key in ("text", "content"):
            if key in value:
                parts.extend(_tool_result_text_parts(value[key]))
        return parts
    return []


def _tool_result_lines(texts: list[str]) -> list[str]:
    lines: list[str] = []
    for text in texts:
        lines.extend(line for line in text.splitlines() if line.strip())
    return lines


def _shape_counts(lines: list[str]) -> dict[str, int]:
    counts = {
        "file_listing": 0,
        "search_grep": 0,
        "sql_table": 0,
        "github_ticket_list": 0,
        "test_output": 0,
        "command_stream": 0,
        "unknown": 0,
    }
    for line in lines:
        matched = False
        if _GREP_RESULT_RE.search(line):
            counts["search_grep"] += 1
            matched = True
        if _SQL_TABLE_RE.search(line) or _SQL_BORDER_RE.search(line):
            counts["sql_table"] += 1
            matched = True
        if _ISSUE_LIST_RE.search(line):
            counts["github_ticket_list"] += 1
            matched = True
        if _TEST_RESULT_RE.search(line):
            counts["test_output"] += 1
            matched = True
        if _COMMAND_STREAM_RE.search(line):
            counts["command_stream"] += 1
            matched = True
        if _FILE_LISTING_RE.search(line):
            counts["file_listing"] += 1
            matched = True
        if not matched:
            counts["unknown"] += 1
    return counts


def _primary_shape(counts: dict[str, int]) -> str:
    ranked = [(shape, count) for shape, count in counts.items() if shape != "unknown" and count > 0]
    if not ranked:
        return "unknown_tool_result"
    ranked.sort(key=lambda item: (-item[1], item[0]))
    shape = ranked[0][0]
    if shape == "search_grep":
        return "search_grep_results"
    if shape == "sql_table":
        return "sql_table_rows"
    if shape == "github_ticket_list":
        return "github_ticket_list"
    if shape == "command_stream":
        return "command_stdout_stderr"
    return shape


def _normalized_line_fingerprint(line: str) -> str:
    return re.sub(r"\s+", " ", line.strip().lower())


def _framing_line(line: str) -> bool:
    stripped = line.strip()
    if not stripped:
        return False
    if len(stripped) > 90:
        return False
    if _ERROR_RE.search(stripped):
        return False
    if _GREP_RESULT_RE.search(stripped) or _SQL_TABLE_RE.search(stripped) or _ISSUE_LIST_RE.search(stripped):
        return False
    if _COMMAND_STREAM_RE.search(stripped):
        return False
    return bool(_TOOL_FRAMING_RE.search(stripped))


def _diff_line_counts(text: str) -> dict[str, int]:
    counts = {
        "added": 0,
        "removed": 0,
        "context": 0,
        "hunks": 0,
        "files": 0,
        "headers": 0,
        "diff_lines": 0,
    }
    seen_files = 0
    for line in text.splitlines():
        if _DIFF_HUNK_RE.match(line):
            counts["hunks"] += 1
            counts["headers"] += 1
            counts["diff_lines"] += 1
            continue
        if _DIFF_HEADER_RE.match(line):
            counts["headers"] += 1
            counts["diff_lines"] += 1
            if line.startswith("diff --git ") or line.startswith("--- ") or line.startswith("+++ "):
                seen_files += 1
            continue
        if line.startswith("+") and not line.startswith("+++"):
            counts["added"] += 1
            counts["diff_lines"] += 1
            continue
        if line.startswith("-") and not line.startswith("---"):
            counts["removed"] += 1
            counts["diff_lines"] += 1
            continue
        if line.startswith(" "):
            counts["context"] += 1
            counts["diff_lines"] += 1
    counts["files"] = seen_files // 2 if seen_files >= 2 and not re.search(r"^diff --git ", text, re.MULTILINE) else len(re.findall(r"^diff --git ", text, re.MULTILINE))
    if counts["files"] <= 0 and counts["hunks"] > 0:
        counts["files"] = 1
    return counts


def _contains_diff(text: str) -> bool:
    counts = _diff_line_counts(text)
    return counts["hunks"] > 0 or (
        counts["headers"] >= 2
        and counts["added"] + counts["removed"] > 0
    )


def _minified_line(line: str) -> bool:
    stripped = line.strip()
    if len(stripped) < 500:
        return False
    if " " in stripped[:500] and stripped[:500].count(" ") > 30:
        return False
    punctuation = sum(stripped.count(char) for char in "{}[]();,:")
    return punctuation >= 40 or len(stripped) >= 1200


def _artifact_counts(text: str) -> dict[str, int]:
    lines = text.splitlines()
    non_empty = [line for line in lines if line.strip()]
    generated_lines = sum(1 for line in non_empty if _GENERATED_MARKER_RE.search(line))
    minified_lines = sum(1 for line in non_empty if _minified_line(line))
    lockfile_present = bool(_LOCKFILE_RE.search(text))
    compiled_present = bool(_COMPILED_ARTIFACT_RE.search(text))
    return {
        "line_count": len(non_empty),
        "generated_marker_lines": generated_lines,
        "minified_lines": minified_lines,
        "lockfile_present": int(lockfile_present),
        "compiled_present": int(compiled_present),
    }


def _generated_likelihood_bucket(text: str) -> str:
    counts = _artifact_counts(text)
    score = 0
    if counts["generated_marker_lines"] > 0:
        score += 2
    if counts["minified_lines"] > 0:
        score += 2
    if counts["lockfile_present"]:
        score += 2
    if counts["compiled_present"]:
        score += 1
    if counts["line_count"] >= 200 and counts["generated_marker_lines"] > 0:
        score += 1
    if score <= 0:
        return "none"
    if score <= 1:
        return "low"
    if score <= 3:
        return "medium"
    return "high"


def _compact_repeated_diff_context_text(text: str) -> tuple[str, int, int]:
    lines = text.splitlines()
    if not any(_DIFF_HUNK_RE.match(line) for line in lines):
        return text, 0, 0
    seen_context: set[str] = set()
    output: list[str] = []
    removed = 0
    in_hunk = False
    for line in lines:
        if _DIFF_HUNK_RE.match(line):
            in_hunk = True
            output.append(line)
            continue
        if _DIFF_HEADER_RE.match(line):
            in_hunk = False
            output.append(line)
            continue
        if in_hunk and line.startswith(" "):
            key = _normalized_line_fingerprint(line)
            if key in seen_context and len(line.strip()) >= 12:
                removed += 1
                continue
            seen_context.add(key)
        output.append(line)
    if removed == 0:
        return text, 0, 0
    compacted = "\n".join(output)
    if text.endswith("\n"):
        compacted += "\n"
    return compacted, max(0, len(text) - len(compacted)), removed


def _compact_generated_artifact_text(text: str) -> tuple[str, int, int]:
    lines = text.splitlines()
    output: list[str] = []
    removed = 0
    saved = 0
    seen_generated: set[str] = set()
    for line in lines:
        normalized = _normalized_line_fingerprint(line)
        if (
            _GENERATED_MARKER_RE.search(line)
            and normalized in seen_generated
            and len(line.strip()) <= 160
        ):
            removed += 1
            saved += len(line) + 1
            continue
        if _GENERATED_MARKER_RE.search(line):
            seen_generated.add(normalized)
        if _minified_line(line):
            keep_head = line[:240]
            keep_tail = line[-160:]
            replacement = (
                f"{keep_head}\n"
                f"[AgentFlow: generated/minified bulk omitted; original_chars={len(line)}]\n"
                f"{keep_tail}"
            )
            if len(replacement) < len(line):
                output.append(replacement)
                removed += 1
                saved += len(line) - len(replacement)
                continue
        output.append(line)
    if removed == 0:
        return text, 0, 0
    compacted = "\n".join(output)
    if text.endswith("\n"):
        compacted += "\n"
    return compacted, max(0, saved), removed


def _compact_text_value(value: Any, compact_func) -> tuple[Any, int, int]:
    if isinstance(value, str):
        return compact_func(value)
    if isinstance(value, list):
        changed_items: list[Any] = []
        saved = 0
        removed = 0
        for item in value:
            new_item, item_saved, item_removed = _compact_text_value(item, compact_func)
            changed_items.append(new_item)
            saved += item_saved
            removed += item_removed
        return changed_items, saved, removed
    if isinstance(value, dict):
        out = copy.deepcopy(value)
        saved = 0
        removed = 0
        for key, child in list(out.items()):
            out[key], item_saved, item_removed = _compact_text_value(child, compact_func)
            saved += item_saved
            removed += item_removed
        return out, saved, removed
    return value, 0, 0


def _compact_repeated_tool_framing_text(text: str) -> tuple[str, int, int]:
    lines = text.splitlines()
    seen: set[str] = set()
    output: list[str] = []
    removed = 0
    for line in lines:
        key = _normalized_line_fingerprint(line)
        if _framing_line(line) and key in seen:
            removed += 1
            continue
        if _framing_line(line):
            seen.add(key)
        output.append(line)
    if removed == 0:
        return text, 0, 0
    compacted = "\n".join(output)
    if text.endswith("\n"):
        compacted += "\n"
    return compacted, max(0, len(text) - len(compacted)), removed


def _compact_tool_result_value(value: Any) -> tuple[Any, int, int]:
    if isinstance(value, str):
        return _compact_repeated_tool_framing_text(value)
    if isinstance(value, list):
        changed_items: list[Any] = []
        saved = 0
        removed = 0
        for item in value:
            new_item, item_saved, item_removed = _compact_tool_result_value(item)
            changed_items.append(new_item)
            saved += item_saved
            removed += item_removed
        return changed_items, saved, removed
    if isinstance(value, dict):
        out = copy.deepcopy(value)
        saved = 0
        removed = 0
        for key in ("text", "content"):
            if key in out:
                out[key], item_saved, item_removed = _compact_tool_result_value(out[key])
                saved += item_saved
                removed += item_removed
        return out, saved, removed
    return value, 0, 0


class ToolResultPatternModule(LocalPatternModule):
    family = "tool_results"
    version = "2026-06-09.1"
    feature_schema = TOOL_RESULT_FEATURE_SCHEMA
    supports_local_crunch = True

    def detect(self, context: PatternModuleContext) -> PatternDetection:
        blocks = _iter_tool_result_blocks(context.body)
        detected = bool(blocks)
        return PatternDetection(
            detected=detected,
            reason="tool-result-blocks-detected" if detected else "no-tool-result-blocks",
            confidence="high" if detected else "none",
        )

    def features(self, context: PatternModuleContext, detection: PatternDetection) -> dict[str, Any]:
        blocks = _iter_tool_result_blocks(context.body)
        texts: list[str] = []
        for entry in blocks:
            block = entry["block"]
            if isinstance(block, dict):
                texts.extend(_tool_result_text_parts(block.get("content")))
        lines = _tool_result_lines(texts)
        normalized_lines = [_normalized_line_fingerprint(line) for line in lines if line.strip()]
        unique_lines = set(normalized_lines)
        duplicate_lines = max(0, len(normalized_lines) - len(unique_lines))
        counts = _shape_counts(lines)
        framing_lines = sum(1 for line in lines if _framing_line(line))
        mixed_prompt_text = any(
            isinstance(message, dict)
            and isinstance(message.get("content"), list)
            and any(isinstance(block, dict) and block.get("type") == "text" for block in message.get("content") or [])
            and any(isinstance(block, dict) and block.get("type") == "tool_result" for block in message.get("content") or [])
            for message in context.body.get("messages") or []
        )
        error_present = any(_ERROR_RE.search(line) for line in lines)
        primary = _primary_shape(counts)
        exactness_required = error_present or primary in {
            "search_grep_results",
            "sql_table_rows",
            "github_ticket_list",
            "test_output",
            "command_stdout_stderr",
        }
        current_state_evidence = primary in {
            "file_listing",
            "search_grep_results",
            "sql_table_rows",
            "github_ticket_list",
            "test_output",
            "command_stdout_stderr",
        }
        return {
            "schema": self.feature_schema,
            "module_family": self.family,
            "module_version": self.version,
            "detected": detection.detected,
            "result_count_bucket": _count_bucket(len(blocks)),
            "tool_result_char_bucket": _text_bucket(sum(len(text) for text in texts)),
            "row_count_bucket": _count_bucket(len(lines)),
            "unique_item_count_bucket": _count_bucket(len(unique_lines)),
            "duplicate_result_fraction_bucket": _fraction_bucket(duplicate_lines, len(normalized_lines)),
            "repeated_framing_line_count_bucket": _count_bucket(framing_lines),
            "primary_result_shape": primary,
            "shape_count_buckets": {shape: _count_bucket(count) for shape, count in counts.items()},
            "error_presence": bool(error_present),
            "current_state_evidence_hint": bool(current_state_evidence),
            "exactness_required_hint": bool(exactness_required),
            "mixed_prompt_tool_result": bool(mixed_prompt_text),
            "safe_local_crunch_hint": bool(framing_lines >= 2),
            "privacy": {
                "metadata_only": True,
                "raw_tool_payload_included": False,
                "raw_tool_result_text_included": False,
                "file_paths_included": False,
                "issue_ids_included": False,
                "row_values_included": False,
                "diagnostic_lines_included": False,
            },
        }

    def apply_local_crunch(
        self,
        body: dict[str, Any],
        context: PatternModuleContext,
        detection: PatternDetection,
    ) -> PatternCrunchResult:
        new_body = copy.deepcopy(body)
        saved = 0
        removed_lines = 0
        for entry in _iter_tool_result_blocks(new_body):
            block = entry["block"]
            if not isinstance(block, dict) or "content" not in block:
                continue
            block["content"], item_saved, item_removed = _compact_tool_result_value(block["content"])
            saved += item_saved
            removed_lines += item_removed
        return PatternCrunchResult(
            body=new_body,
            changed=removed_lines > 0,
            saved_chars=saved,
            reason="safe-repeated-framing-compacted" if removed_lines else "no-safe-repeated-framing",
        )


class DiffPatternModule(LocalPatternModule):
    family = "diffs"
    version = "2026-06-09.1"
    feature_schema = DIFF_FEATURE_SCHEMA
    supports_local_crunch = True

    def detect(self, context: PatternModuleContext) -> PatternDetection:
        detected = _contains_diff(context.text)
        return PatternDetection(
            detected=detected,
            reason="diff-signals-detected" if detected else "no-diff-signals",
            confidence="high" if detected else "none",
        )

    def features(self, context: PatternModuleContext, detection: PatternDetection) -> dict[str, Any]:
        counts = _diff_line_counts(context.text)
        changed_lines = counts["added"] + counts["removed"]
        exact_requested = bool(_EXACT_REQUEST_RE.search(context.text))
        return {
            "schema": self.feature_schema,
            "module_family": self.family,
            "module_version": self.version,
            "detected": detection.detected,
            "diff_present": bool(detection.detected),
            "multi_file_diff": counts["files"] > 1,
            "diff_file_count_bucket": _count_bucket(counts["files"]),
            "hunk_count_bucket": _count_bucket(counts["hunks"]),
            "added_removed_line_count_bucket": _count_bucket(changed_lines),
            "unchanged_context_fraction_bucket": _fraction_bucket(counts["context"], counts["diff_lines"]),
            "exact_artifact_requested_hint": exact_requested,
            "changed_hunks_preserved_by_default": True,
            "safe_local_crunch_hint": bool(counts["context"] >= 8 and not exact_requested),
            "privacy": {
                "metadata_only": True,
                "raw_diff_included": False,
                "raw_patch_included": False,
                "raw_content_included": False,
                "file_paths_included": False,
                "changed_lines_included": False,
            },
        }

    def apply_local_crunch(
        self,
        body: dict[str, Any],
        context: PatternModuleContext,
        detection: PatternDetection,
    ) -> PatternCrunchResult:
        if _EXACT_REQUEST_RE.search(context.text):
            return PatternCrunchResult(
                body=body,
                changed=False,
                reason="exact-diff-request-preserved",
            )
        new_body, saved, removed = _compact_text_value(body, _compact_repeated_diff_context_text)
        return PatternCrunchResult(
            body=new_body,
            changed=removed > 0,
            saved_chars=saved,
            reason="safe-repeated-diff-context-compacted" if removed else "no-safe-repeated-diff-context",
        )


class GeneratedArtifactPatternModule(LocalPatternModule):
    family = "generated_artifacts"
    version = "2026-06-09.1"
    feature_schema = GENERATED_ARTIFACT_FEATURE_SCHEMA
    supports_local_crunch = True

    def detect(self, context: PatternModuleContext) -> PatternDetection:
        counts = _artifact_counts(context.text)
        detected = (
            counts["lockfile_present"] > 0
            or counts["generated_marker_lines"] > 0
            or counts["minified_lines"] > 0
            or counts["compiled_present"] > 0
        )
        return PatternDetection(
            detected=detected,
            reason="generated-artifact-signals-detected" if detected else "no-generated-artifact-signals",
            confidence="high" if detected else "none",
        )

    def features(self, context: PatternModuleContext, detection: PatternDetection) -> dict[str, Any]:
        counts = _artifact_counts(context.text)
        exact_requested = bool(_EXACT_REQUEST_RE.search(context.text))
        dependency_task = bool(_DEPENDENCY_TASK_RE.search(context.text))
        return {
            "schema": self.feature_schema,
            "module_family": self.family,
            "module_version": self.version,
            "detected": detection.detected,
            "generated_file_likelihood_bucket": _generated_likelihood_bucket(context.text),
            "lockfile_present": bool(counts["lockfile_present"]),
            "minified_content_fraction_bucket": _fraction_bucket(counts["minified_lines"], counts["line_count"]),
            "generated_marker_count_bucket": _count_bucket(counts["generated_marker_lines"]),
            "compiled_artifact_hint": bool(counts["compiled_present"]),
            "exact_artifact_requested_hint": exact_requested,
            "dependency_resolution_task_hint": dependency_task,
            "exact_artifact_preserved_by_default": bool(exact_requested or dependency_task or counts["lockfile_present"]),
            "safe_local_crunch_hint": bool(
                not exact_requested
                and not (dependency_task and counts["lockfile_present"])
                and (counts["minified_lines"] > 0 or counts["generated_marker_lines"] > 1)
            ),
            "privacy": {
                "metadata_only": True,
                "raw_artifact_included": False,
                "raw_content_included": False,
                "file_paths_included": False,
                "dependency_names_included": False,
                "line_values_included": False,
            },
        }

    def apply_local_crunch(
        self,
        body: dict[str, Any],
        context: PatternModuleContext,
        detection: PatternDetection,
    ) -> PatternCrunchResult:
        counts = _artifact_counts(context.text)
        if _EXACT_REQUEST_RE.search(context.text):
            return PatternCrunchResult(
                body=body,
                changed=False,
                reason="exact-artifact-request-preserved",
            )
        if counts["lockfile_present"] and _DEPENDENCY_TASK_RE.search(context.text):
            return PatternCrunchResult(
                body=body,
                changed=False,
                reason="dependency-resolution-artifact-preserved",
            )
        new_body, saved, removed = _compact_text_value(body, _compact_generated_artifact_text)
        return PatternCrunchResult(
            body=new_body,
            changed=removed > 0,
            saved_chars=saved,
            reason="safe-generated-artifact-bulk-compacted" if removed else "no-safe-generated-artifact-bulk",
        )


def _split_pipe_cells(line: str) -> list[str]:
    stripped = line.strip().strip("|")
    return [cell.strip() for cell in stripped.split("|")]


def _table_sample_sufficient_bucket(
    *,
    row_count: int,
    aggregation: bool,
    exact_lookup: bool,
    reconciliation: bool,
    current_state: bool,
    user_specific: bool,
) -> str:
    if exact_lookup or reconciliation or current_state:
        return "low"
    if aggregation and row_count >= 25 and not user_specific:
        return "high"
    if aggregation and row_count >= 10:
        return "medium"
    if row_count >= 50 and not user_specific:
        return "medium"
    return "low"


def _tabular_shapes_from_text(text: str) -> list[dict[str, int | str]]:
    shapes: list[dict[str, int | str]] = []
    lines = [line for line in text.splitlines() if line.strip()]

    pipe_rows: list[list[str]] = []
    pipe_separator = False
    sql_border = False
    for line in lines:
        if _SQL_BORDER_LINE_RE.match(line):
            sql_border = True
            continue
        if "|" not in line:
            continue
        if _PIPE_SEPARATOR_RE.match(line):
            pipe_separator = True
            continue
        cells = _split_pipe_cells(line)
        if len(cells) >= 2:
            pipe_rows.append(cells)
    if len(pipe_rows) >= 2 and (pipe_separator or sql_border):
        column_counts = [len(row) for row in pipe_rows]
        mode_columns = max(set(column_counts), key=column_counts.count)
        shapes.append({
            "shape": "sql_result_rows" if sql_border else "markdown_table",
            "rows": max(0, len(pipe_rows) - 1),
            "columns": mode_columns,
            "schema_repeated": column_counts.count(mode_columns),
            "schema_total": len(column_counts),
        })

    for delimiter, shape_name in ((",", "csv_block"), ("\t", "tsv_block")):
        best_rows = 0
        best_columns = 0
        best_repeated = 0
        current_columns: list[int] = []
        for line in lines + [""]:
            if delimiter in line and not line.lstrip().startswith(("{", "[")):
                columns = [cell.strip() for cell in line.split(delimiter)]
                if len(columns) >= 2 and any(cell for cell in columns):
                    current_columns.append(len(columns))
                    continue
            if len(current_columns) >= 3:
                mode_columns = max(set(current_columns), key=current_columns.count)
                if current_columns.count(mode_columns) > best_repeated:
                    best_rows = len(current_columns)
                    best_columns = mode_columns
                    best_repeated = current_columns.count(mode_columns)
            current_columns = []
        if best_rows >= 3 and best_columns >= 2:
            shapes.append({
                "shape": shape_name,
                "rows": max(0, best_rows - 1),
                "columns": best_columns,
                "schema_repeated": best_repeated,
                "schema_total": best_rows,
            })

    decoder = json.JSONDecoder()
    for match in _JSON_ARRAY_START_RE.finditer(text):
        try:
            value, _end = decoder.raw_decode(text[match.start():])
        except json.JSONDecodeError:
            continue
        if not (
            isinstance(value, list)
            and len(value) >= 2
            and all(isinstance(item, dict) for item in value)
        ):
            continue
        key_sets = [tuple(sorted(str(key) for key in item.keys())) for item in value if isinstance(item, dict)]
        if not key_sets:
            continue
        mode_schema = max(set(key_sets), key=key_sets.count)
        shapes.append({
            "shape": "json_object_array",
            "rows": len(key_sets),
            "columns": len(mode_schema),
            "schema_repeated": key_sets.count(mode_schema),
            "schema_total": len(key_sets),
        })
        break
    return shapes


def _primary_tabular_shape(shapes: list[dict[str, int | str]]) -> dict[str, int | str] | None:
    if not shapes:
        return None
    return sorted(shapes, key=lambda item: (-int(item.get("rows") or 0), str(item.get("shape") or "")))[0]


class TabularDataPatternModule(LocalPatternModule):
    family = "tabular_data"
    version = "2026-06-10.1"
    feature_schema = TABULAR_DATA_FEATURE_SCHEMA
    supports_local_crunch = False

    def detect(self, context: PatternModuleContext) -> PatternDetection:
        detected = bool(_tabular_shapes_from_text(context.text))
        return PatternDetection(
            detected=detected,
            reason="tabular-data-signals-detected" if detected else "no-tabular-data-signals",
            confidence="high" if detected else "none",
        )

    def features(self, context: PatternModuleContext, detection: PatternDetection) -> dict[str, Any]:
        shapes = _tabular_shapes_from_text(context.text)
        primary = _primary_tabular_shape(shapes) or {}
        primary_shape = str(primary.get("shape") or "unknown")
        rows = int(primary.get("rows") or 0)
        columns = int(primary.get("columns") or 0)
        schema_repeated = int(primary.get("schema_repeated") or 0)
        schema_total = int(primary.get("schema_total") or 0)
        exact_lookup = bool(_EXACT_LOOKUP_RE.search(context.text))
        aggregation = bool(_AGGREGATION_RE.search(context.text))
        reconciliation = bool(_RECONCILIATION_RE.search(context.text))
        current_state = bool(_CURRENT_STATE_RE.search(context.text) or primary_shape == "sql_result_rows")
        user_specific = bool(_USER_SPECIFIC_RE.search(context.text))
        preserve_exact = bool(exact_lookup or reconciliation or current_state)
        return {
            "schema": self.feature_schema,
            "module_family": self.family,
            "module_version": self.version,
            "detected": detection.detected,
            "table_present": bool(shapes),
            "table_shape": primary_shape,
            "table_count_bucket": _count_bucket(len(shapes)),
            "row_count_bucket": _count_bucket(rows),
            "column_count_bucket": _count_bucket(columns),
            "schema_repetition_bucket": _fraction_bucket(schema_repeated, schema_total),
            "exact_lookup_requested_hint": exact_lookup,
            "aggregation_requested_hint": aggregation,
            "reconciliation_requested_hint": reconciliation,
            "time_sensitive_hint": current_state,
            "user_specific_hint": user_specific,
            "sample_sufficient_likelihood_bucket": _table_sample_sufficient_bucket(
                row_count=rows,
                aggregation=aggregation,
                exact_lookup=exact_lookup,
                reconciliation=reconciliation,
                current_state=current_state,
                user_specific=user_specific,
            ),
            "exact_rows_preserved_by_default": preserve_exact,
            "safe_local_crunch_hint": bool(aggregation and not preserve_exact and rows >= 10),
            "privacy": {
                "metadata_only": True,
                "raw_table_rows_included": False,
                "row_values_included": False,
                "column_names_included": False,
                "user_values_included": False,
            },
        }


def _deterministic_answer_bucket(
    *,
    static_information: bool,
    time_sensitive: bool,
    user_specific: bool,
    exact_lookup: bool,
    reconciliation: bool,
) -> str:
    if time_sensitive or user_specific or reconciliation:
        return "low"
    if static_information and not exact_lookup:
        return "high"
    if static_information or exact_lookup:
        return "medium"
    return "low"


def _cacheability_bucket(
    *,
    deterministic_bucket: str,
    time_sensitive: bool,
    user_specific: bool,
    exact_lookup: bool,
    reconciliation: bool,
    has_tools: bool,
) -> str:
    if time_sensitive or user_specific or reconciliation or has_tools:
        return "low"
    if deterministic_bucket == "high" and not exact_lookup:
        return "high"
    if deterministic_bucket in {"high", "medium"}:
        return "medium"
    return "low"


class CacheabilityPatternModule(LocalPatternModule):
    family = "cacheability"
    version = "2026-06-10.1"
    feature_schema = CACHEABILITY_FEATURE_SCHEMA
    supports_local_crunch = False

    def detect(self, context: PatternModuleContext) -> PatternDetection:
        text = context.text.strip()
        static_information = bool(_STATIC_INFORMATION_RE.search(text))
        time_sensitive = bool(_CURRENT_STATE_RE.search(text))
        user_specific = bool(_USER_SPECIFIC_RE.search(text))
        exact_lookup = bool(_EXACT_LOOKUP_RE.search(text))
        reconciliation = bool(_RECONCILIATION_RE.search(text))
        detected = bool(text and (static_information or time_sensitive or user_specific or exact_lookup or reconciliation))
        return PatternDetection(
            detected=detected,
            reason="cacheability-signals-detected" if detected else "no-cacheability-signals",
            confidence="medium" if detected else "none",
        )

    def features(self, context: PatternModuleContext, detection: PatternDetection) -> dict[str, Any]:
        text = context.text.strip()
        static_information = bool(_STATIC_INFORMATION_RE.search(text))
        time_sensitive = bool(_CURRENT_STATE_RE.search(text))
        user_specific = bool(_USER_SPECIFIC_RE.search(text))
        exact_lookup = bool(_EXACT_LOOKUP_RE.search(text))
        aggregation = bool(_AGGREGATION_RE.search(text))
        reconciliation = bool(_RECONCILIATION_RE.search(text))
        has_tools = "tool" in str(context.category or "").lower()
        deterministic_bucket = _deterministic_answer_bucket(
            static_information=static_information,
            time_sensitive=time_sensitive,
            user_specific=user_specific,
            exact_lookup=exact_lookup,
            reconciliation=reconciliation,
        )
        cache_bucket = _cacheability_bucket(
            deterministic_bucket=deterministic_bucket,
            time_sensitive=time_sensitive,
            user_specific=user_specific,
            exact_lookup=exact_lookup,
            reconciliation=reconciliation,
            has_tools=has_tools,
        )
        return {
            "schema": self.feature_schema,
            "module_family": self.family,
            "module_version": self.version,
            "detected": detection.detected,
            "cacheability_bucket": cache_bucket,
            "deterministic_answer_likelihood_bucket": deterministic_bucket,
            "static_information_hint": static_information,
            "time_sensitive_hint": time_sensitive,
            "user_specific_hint": user_specific,
            "exact_lookup_requested_hint": exact_lookup,
            "aggregation_requested_hint": aggregation,
            "reconciliation_requested_hint": reconciliation,
            "provider_tool_context_hint": has_tools,
            "exact_cache_candidate_hint": bool(cache_bucket in {"high", "medium"} and not has_tools),
            "cache_preserved_by_default_reason": (
                "time-sensitive" if time_sensitive else
                "user-specific" if user_specific else
                "reconciliation" if reconciliation else
                "tool-context" if has_tools else
                "exact-lookup" if exact_lookup else
                "none"
            ),
            "privacy": {
                "metadata_only": True,
                "raw_text_included": False,
                "user_values_included": False,
                "identifiers_included": False,
                "current_state_values_included": False,
            },
        }


DEFAULT_PATTERN_MODULE_REGISTRY = PatternModuleRegistry([
    CacheabilityPatternModule(),
    DiffPatternModule(),
    GeneratedArtifactPatternModule(),
    PromptRolePatternModule(),
    TabularDataPatternModule(),
    TerminalLogPatternModule(),
    ToolResultPatternModule(),
])


def registered_pattern_modules(registry: PatternModuleRegistry | None = None) -> list[dict[str, Any]]:
    active = registry or DEFAULT_PATTERN_MODULE_REGISTRY
    return [
        {
            "family": module.family,
            "version": module.version,
            "feature_schema": module.feature_schema,
            "enabled_by_default": module.enabled_by_default,
            "supports_local_crunch": module.supports_local_crunch,
        }
        for module in active.modules()
    ]


def _module_setting(settings: dict[str, Any] | None, family: str) -> dict[str, Any]:
    if not isinstance(settings, dict):
        return {}
    raw = settings.get(family)
    if isinstance(raw, dict):
        return raw
    if isinstance(raw, bool):
        return {"enabled": raw}
    return {}


def _as_bool(value: Any, default: bool) -> bool:
    if value is None:
        return default
    if isinstance(value, bool):
        return value
    if isinstance(value, (int, float)):
        return bool(value)
    if isinstance(value, str):
        return value.strip().lower() not in {"0", "false", "no", "off", ""}
    return default


def _safe_feature_entry(module: LocalPatternModule, features: dict[str, Any]) -> dict[str, Any]:
    return {
        "family": module.family,
        "version": module.version,
        "feature_schema": module.feature_schema,
        "features": features,
    }


def _privacy_guard_meta(violations: list[dict[str, str]]) -> dict[str, Any]:
    return {
        "schema": "agentflow.local_pattern_module_privacy_guard.v1",
        "safe": not violations,
        "violation_count": len(violations),
        "blocked_keys": sorted({item.get("key", "unknown") for item in violations}),
        "first_violation_path": violations[0].get("path") if violations else None,
        "raw_values_logged": False,
    }


def evaluate_pattern_modules(
    body: dict[str, Any],
    *,
    module_settings: dict[str, Any] | None = None,
    registry: PatternModuleRegistry | None = None,
    apply_local_crunch: bool = True,
    policy_source: str = "local-default",
    rule_path: str | None = None,
    category: str | None = None,
) -> tuple[dict[str, Any], dict[str, Any]]:
    active = registry or DEFAULT_PATTERN_MODULE_REGISTRY
    current_body = copy.deepcopy(body)
    server_features: list[dict[str, Any]] = []
    module_metas: list[dict[str, Any]] = []
    total_saved_chars = 0

    for module in active.modules():
        setting = _module_setting(module_settings, module.family)
        enabled = _as_bool(setting.get("enabled"), module.enabled_by_default)
        local_crunch_enabled = _as_bool(setting.get("local_crunch_enabled"), False)
        base_meta = {
            "family": module.family,
            "version": module.version,
            "enabled": enabled,
            "supports_local_crunch": module.supports_local_crunch,
            "local_crunch_enabled": local_crunch_enabled,
        }
        if not enabled:
            meta = module.outcome_metadata(
                status="skipped",
                reason="disabled",
                detection=None,
                features=None,
                changed=False,
                saved_chars=0,
            )
            meta.update(base_meta)
            module_metas.append(meta)
            continue

        context = PatternModuleContext(
            body=current_body,
            text=_extract_text(current_body),
            category=category,
            policy_source=policy_source,
            rule_path=rule_path,
        )
        detection = module.detect(context)
        if not detection.detected:
            meta = module.outcome_metadata(
                status="skipped",
                reason=detection.reason,
                detection=detection,
                features=None,
                changed=False,
                saved_chars=0,
            )
            meta.update(base_meta)
            module_metas.append(meta)
            continue

        features = module.features(context, detection)
        feature_entry = _safe_feature_entry(module, features)
        violations = managed_egress_violations(feature_entry)
        if violations:
            meta = module.outcome_metadata(
                status="bypass",
                reason="privacy-guard-rejected",
                detection=detection,
                features=None,
                changed=False,
                saved_chars=0,
            )
            meta.update(base_meta)
            meta["privacy_guard"] = _privacy_guard_meta(violations)
            module_metas.append(meta)
            continue

        changed = False
        saved_chars = 0
        reason = "feature-only-no-local-crunch"
        status = "skipped"
        if apply_local_crunch and local_crunch_enabled and module.supports_local_crunch:
            before_chars = len(stable_json(current_body))
            crunch_result = module.apply_local_crunch(current_body, context, detection)
            current_body = crunch_result.body
            after_chars = len(stable_json(current_body))
            changed = bool(crunch_result.changed or before_chars != after_chars)
            saved_chars = max(0, int(crunch_result.saved_chars or before_chars - after_chars))
            reason = crunch_result.reason
            status = "applied" if changed else "skipped"
            total_saved_chars += saved_chars

        server_features.append(feature_entry)
        meta = module.outcome_metadata(
            status=status,
            reason=reason,
            detection=detection,
            features=features,
            changed=changed,
            saved_chars=saved_chars,
        )
        meta.update(base_meta)
        meta["feature_schema"] = module.feature_schema
        meta["privacy_guard"] = _privacy_guard_meta([])
        meta["feature_summary"] = {
            "family": module.family,
            "version": module.version,
            "feature_schema": module.feature_schema,
            "text_bucket": _text_bucket(len(context.text)),
            "category": category or "unknown",
            "raw_content_included": False,
        }
        module_metas.append(meta)

    server_feature_bundle = {
        "schema": PATTERN_MODULE_FEATURES_SCHEMA,
        "module_feature_count": len(server_features),
        "features": server_features,
        "privacy": {
            "metadata_only": True,
            "raw_content_included": False,
            "raw_provider_body_included": False,
            "raw_tool_payload_included": False,
        },
    }
    server_violations = managed_egress_violations(server_feature_bundle)
    if server_violations:
        server_feature_bundle = {
            "schema": PATTERN_MODULE_FEATURES_SCHEMA,
            "module_feature_count": 0,
            "features": [],
            "privacy": {
                "metadata_only": True,
                "raw_content_included": False,
                "raw_provider_body_included": False,
                "raw_tool_payload_included": False,
            },
            "privacy_guard": _privacy_guard_meta(server_violations),
        }

    meta = {
        "schema": PATTERN_MODULES_SCHEMA,
        "registered_count": len(active.modules()),
        "enabled_count": sum(1 for item in module_metas if item.get("enabled")),
        "detected_count": sum(1 for item in module_metas if item.get("detected")),
        "features_emitted_count": len(server_features),
        "applied_count": sum(1 for item in module_metas if item.get("status") == "applied"),
        "bypass_count": sum(1 for item in module_metas if item.get("status") == "bypass"),
        "saved_chars": total_saved_chars,
        "tokens_saved_est": total_saved_chars // TOKEN_CHARS,
        "policy_source": policy_source,
        "rule_path": rule_path,
        "modules": module_metas,
        "server_features": server_feature_bundle,
        "raw_content_included": False,
    }
    return current_body, meta
